title: SB Discord Docs
description: Documentation for the Streamerbot Extension that adds a Discord bot to Streamerbot
theme: just-the-docs

color_scheme: dark

url: https://kitzyangel.github.io/streamerbot-discord-ext-docs

aux_links:
  Docs Repo: https://github.com/KitzyAngel/streamerbot-discord-ext-docs
