title: SB Discord Docs
description: Documentation for the Streamerbot Extension that adds a Discord bot to Streamerbot
theme: just-the-docs

color_scheme: dark

url: https://kitzyangel.github.io/streamerbot-discord-ext-docs

aux_links:
  Docs Repo: https://github.com/KitzyAngel/streamerbot-discord-ext-docs

nav_external_links:
  - title: Discord Gateway Events
    url: https://docs.discord.com/developers/events/gateway-events
    opens_in_new_tab: true
  - title: Discord HTTP API
    url: https://docs.discord.com/developers/resources/message
    opens_in_new_tab: true
  - title: Twitch HTTP API
    url: https://dev.twitch.tv/docs/api/reference/
    opens_in_new_tab: true